### ISSUE TITLE
Tooltip cannot be seen if widget is at bottom of window

### ISSUE THREAD

**Issue by hntechsoftware** [gnikit/tkinter-tooltip#90] opened 2024-03-09 09:17 UTC
Since the tooltip position is south east of the widget it is binded to, it doesn't work it the widget is at the bottom of the screen. A suggested feature is to either allow the user to control in what direction the tooltip is displayed or setup some automated way to do it by calculating from window size or maximize, position, etc.

**Comment by gnikit** [comment] 2024-05-09 11:37
Duplicate of #7.
Let's try and keep the discussion and brainstorming solutions in one place.

**Closed by gnikit** 2024-05-09 11:37 UTC

**Comment by hntechsoftware** [comment] 2024-05-09 12:32
Sorry, should've known better.

Also, I found an alternative solution. There are the optional properties x_offset and y_offset which can modified for each individual tooltip when declaring it. That solved my problem

**Comment by gnikit** [comment] 2024-05-09 12:37
Glad to hear you found a workaround. Generally, the underlying issue you pointed to is quite annoying because when the existing solution fails the tooltip goes out of bounds, but if we force the tooltip to remain within the parent widget and the parent widget is not large enough to host the tooltip's message then it will be an unreadable mess.

I am not sure how to address both edge-cases (and I admit that I have not looked much for a solution either).
